### ISSUE TITLE
Validation of the creation of the material

### ISSUE THREAD

**Issue by Vorobushec** [texttree/community-check-app#18]
Некорретное использование upsertMaterial.  Upsert позволяет добавить два материала к проверке или вообще добавить материал к другой.
Также нужно переписать обновление/добавление материала с использованием rpc функции. 

В рлс надо отключить возможность добавлять в базу. 
У одной проверки у нас существует один материал. Связь один к одному. 

1 вариант - добавить в таблицу параметр что check_id должен быть уникальным.
2 вариант - запертить вставку, только редактирование. Добавить триггер, как только создали проверку сразу к ней создать пустой материал. 

Если смотреть на викану, мне кажется там так же устроен бриф. Как только создал ты проект - к нему триггером создается бриф и больше их создавать нельзя.

**Comment by DenisArger** [comment]
![изображение](https://github.com/texttree/community-check-app/assets/24476504/02a84416-dcec-40d3-bc3d-2a3dd9696b3d)

**Comment by DenisArger** [comment]
![изображение](https://github.com/texttree/community-check-app/assets/24476504/9ad044f3-7aea-4133-b069-912d47b4dc25)
