### ISSUE TITLE
Getting notes for checking in one request

### ISSUE THREAD

**Issue by Vorobushec** [texttree/community-check-app#19]
Сейчас это делается двумя запросами, нужно исправить

**Comment by DenisArger** [comment]
@Vorobushec мало информации по ишью. 
"Всё" это что? Нужна более подробна информация. Какая проблема и какое ведется решение?

**Comment by DenisArger** [comment]
Речь про этот код? 
![изображение](https://github.com/texttree/community-check-app/assets/24476504/10c81004-1ec8-4a5a-b835-6f56e1b636cc)

**Comment by foxprogs** [comment]
> Речь про этот код? ![изображение](https://private-user-images.githubusercontent.com/24476504/309221023-10c81004-1ec8-4a5a-b835-6f56e1b636cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Njk5MzksIm5iZiI6MTcwOTY2OTYzOSwicGF0aCI6Ii8yNDQ3NjUwNC8zMDkyMjEwMjMtMTBjODEwMDQtMWVjOC00YTVhLWI4MzUtNmY1NmUxYjYzNmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIwMTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmRhOGQ0MzlhY2FlYmY1NjI4YjI1Y2ZmMzYzN2M2MzFmYjA4ZWY4Y2I5YmQzNDRhYTQ1NjM1NGMyY2M2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZ9XqFMGOnXVmnRafbTwy-cJlRhf5tEvzcgxS9d5fCg)

 @DenisArger да. Тут два запроса, хотя можно сократить до одного.

**Comment by DenisArger** [comment]
@foxprogs спасибо большое за ответ!

**Comment by DenisArger** [comment]
Перепишу через SQL функцию.
