### ISSUE TITLE
создавать проверки, книги, проекты может не только админ

### ISSUE THREAD

**Issue by Vorobushec** [texttree/community-check-app#20]

**Comment by DenisArger** [comment]
@foxprogs @Valyukhov как это должно быть?
Речь про то, чтобы полностью убрать администрирование или просто расширить полномочия обычного пользователя до того, чтобы он смог создавать проверки, книги и проекты?

**Comment by foxprogs** [comment]
> @foxprogs @Valyukhov как это должно быть? Речь про то, чтобы полностью убрать администрирование или просто расширить полномочия обычного пользователя до того, чтобы он смог создавать проверки, книги и проекты?

@DenisArger второе, любой зареганный юзер может создавать проверки. А админ тут наверное будет иметь потом более расширенные права, блокировать пользователей, удалять кривые проекты и т.д.
